drop table if exists member CASCADE;

create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    password varchar(255),
    primary key (id)
);

SELECT * FROM MEMBER

drop table if exists Ramen CASCADE;

create table product
(
    name varchar(255),
    kcal varchar(255),
    protein varchar(255),
    fat varchar(255),
    carbohydrate varchar(255),
    sugar varchar(255)
);

SELECT * FROM Ramen

INSERT INTO Ramen(name, kcal, protein, fat, carbohydrate, sugar) VALUES ('짜파게티', '610', '11', '20', '97', '6');

create table Review
(
    date Date,
    productId int,
    reviewBody text(65535),
    memberId INTEGER generated by default as identity,
    FOREIGN KEY(memberId) REFERENCES member(id),
    primary key(memberId)
);